-- CreateTable
CREATE TABLE "message_stats" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "timestamp" TEXT NOT NULL,
    "conversationFile" TEXT NOT NULL,
    "inputTokens" INTEGER,
    "outputTokens" INTEGER,
    "cacheCreationTokens" INTEGER,
    "cacheReadTokens" INTEGER,
    "cost" DOUBLE PRECISION,
    "model" TEXT,
    "toolCalls" INTEGER,
    "hash" TEXT,
    "filesRead" INTEGER,
    "filesEdited" INTEGER,
    "filesWritten" INTEGER,
    "fileTypes" JSONB,
    "terminalCommands" INTEGER,
    "globSearches" INTEGER,
    "grepSearches" INTEGER,
    "linesRead" INTEGER,
    "linesEdited" INTEGER,
    "linesWritten" INTEGER,
    "bytesRead" INTEGER,
    "bytesEdited" INTEGER,
    "bytesWritten" INTEGER,
    "todosCreated" INTEGER NOT NULL DEFAULT 0,
    "todosCompleted" INTEGER NOT NULL DEFAULT 0,
    "todosInProgress" INTEGER NOT NULL DEFAULT 0,
    "todoWrites" INTEGER NOT NULL DEFAULT 0,
    "todoReads" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "message_stats_pkey" PRIMARY KEY ("id")
);
